// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/6d0e826824da52204c1c93f92cecbc961ac84fa9/ngstorage/ngstorage.d.ts
// Type definitions for ngstorage 0.3.10
// Project: https://github.com/gsklee/ngStorage
// Definitions by: Jakub Pistek <https://github.com/kubiq>
// Definitions: https://github.com/kubiq/DefinitelyTyped


declare namespace angular.storage {

    export interface IStorageService {
        $default(items: {}): IStorageService;
        $reset(items?: {}): IStorageService;
        $apply(): void;

        get<T>(key: string): T;
        set<T>(key: string, value: T): T;
    }

    export interface IStorageProvider extends angular.IServiceProvider {

        get<T>(key:string): T;
        set<T>(key:string, value:T): T;

        setKeyPrefix(prefix: string): void;
        setSerializer(serializer: (value: any)=>string): void;
        setDeserializer(deserializer: (value: string)=>any): void;
    }
}